# Generated by Django 6.0.3 on 2026-04-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('COMBOS', 'Combos'), ('CANCHITA', 'Canchita'), ('BEBIDAS', 'Bebidas'), ('SNACKS', 'Snacks'), ('COLECCIONABLES', 'Coleccionables')], max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AGOTADO', 'Agotado'), ('OCULTO', 'Oculto')], default='DISPONIBLE', max_length=15)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'products',
                'ordering': ['category', 'name'],
            },
        ),
    ]
